input_feature_columns = ['EWO', 'EWO_lag_1', 'EWO_lag_2', 'pre_market_range_change',
       'prev_post_market_range_change', 'pre_market_spread',
       'prev_post_market_spread', 'pre_market_return', 'post_market_return',
       'full_overnight_return', 'PREV_OPEN_avg_1_increment',
       'PREV_OPEN_avg_3_increment', 'PREV_OPEN_avg_5_increment',
       'PREV_OPEN_avg_9_increment', 'PREV_OPEN_avg_12_increment',
       'PREV_CLOSE_avg_1_increment', 'PREV_CLOSE_avg_3_increment',
       'PREV_CLOSE_avg_5_increment', 'PREV_CLOSE_avg_9_increment',
       'PREV_CLOSE_avg_12_increment', 'PREV_HIGH_avg_1_increment',
       'PREV_HIGH_avg_3_increment', 'PREV_HIGH_avg_5_increment',
       'PREV_HIGH_avg_9_increment', 'PREV_HIGH_avg_12_increment',
       'PREV_LOW_avg_1_increment', 'PREV_LOW_avg_3_increment',
       'PREV_LOW_avg_5_increment', 'PREV_LOW_avg_9_increment',
       'PREV_LOW_avg_12_increment', 'pre_market_price_mean_avg_1_increment',
       'pre_market_price_mean_avg_3_increment',
       'pre_market_price_mean_avg_5_increment',
       'pre_market_price_mean_avg_10_increment',
       'pre_market_price_mean_avg_22_increment',
       'pre_market_price_std_avg_3_increment',
       'pre_market_price_std_avg_5_increment',
       'pre_market_price_std_avg_10_increment',
       'PREV_post_market_price_mean_avg_1_increment',
       'PREV_post_market_price_mean_avg_3_increment',
       'PREV_post_market_price_mean_avg_5_increment',
       'PREV_post_market_price_mean_avg_10_increment',
       'PREV_post_market_price_mean_avg_22_increment',
       'PREV_post_market_price_std_avg_3_increment',
       'PREV_post_market_price_std_avg_5_increment',
       'PREV_post_market_price_std_avg_10_increment', 'SYM_ROOT_AAPL',
       'SYM_ROOT_ABBV', 'SYM_ROOT_ADBE', 'SYM_ROOT_AMZN', 'SYM_ROOT_BA',
       'SYM_ROOT_BABA', 'SYM_ROOT_CRM', 'SYM_ROOT_CSCO', 'SYM_ROOT_DIS',
       'SYM_ROOT_GOOG', 'SYM_ROOT_KO', 'SYM_ROOT_MA', 'SYM_ROOT_MSFT',
       'SYM_ROOT_NFLX', 'SYM_ROOT_NVDA', 'SYM_ROOT_SHOP', 'SYM_ROOT_TSLA',
       'SYM_ROOT_TWLO', 'SYM_ROOT_V', 'SYM_ROOT_VOO', 'SYM_ROOT_VTI',
       'DAY_OF_WEEK_Friday', 'DAY_OF_WEEK_Monday', 'DAY_OF_WEEK_Thursday',
       'DAY_OF_WEEK_Tuesday', 'DAY_OF_WEEK_Wednesday',]

print(len(input_feature_columns))